[package]
name = "aegis2067usb"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
api = { path = "../api" }
clap = { version = "4.5.22", features = ["derive"] }
config = "0.14.1"
rust-ini = "0.21.1"
